export const characterData = [
    {
        id: 'anna-diana',
        name: 'Anna Diana (born Anna Maria Veller)',
        image: 'ANNA DIANA.jpg',
        height: '5’5” (165 cm)',
        hair_color: 'Chocolate-brown',
        eye_color: 'Blue',
        blood_type: 'Unknown (part god)',
        birth_date: '24 August 1848',
        relationships: 'Best friends with Christine Gauger, aka “Alina.” Married to Gustav Strehl. Mother of Amy Maria Strehl and Luna, both demigoddesses.',
        additional_info: 'One of the Old Gods, known by various names throughout human history such as Artemis, Diana, and Medeina, but most commonly called simply The Huntress. She was killed ~ 13,500 years ago and reincarnated as a peasant farm girl in the (fictitious) rural village of Weizen, in the far eastern reaches of the Kingdom of Prussia (modern-day Kaliningrad Oblast), along with her friend, Aphrodite/Venus, who was reincarnated as Christine Elisabeth Gauger. Shorn of their past life memories, the pair were targeted by unsavory elements of the Invisible World that recognized them for who they once were.'
    },
    {
        id: 'alina-2',
        name: 'Alina (formerly Christine Gauger)',
        image: 'ALINA.jpg',
        height: '5’6” (167.5 cm)',
        hair_color: 'Platinum-blonde',
        eye_color: 'Green',
        blood_type: 'Unknown (part god)',
        birth_date: '3 March 1848',
        relationships: 'Best friends with Anna Diana. Mother of Metia. Grandmother of Mīlan, Julia, and Luna.',
        additional_info: 'One of the Old Gods, known by various names throughout human history such as Aphrodite, Venus, and The Morning Star. She was killed ~ 13,500 years ago and reincarnated as a peasant farm girl from the (fictitious) rural village of Weizen, in the far eastern reaches of the Kingdom of Prussia (modern-day Kaliningrad Oblast). During a summer solstice ritual she attended with her great aunt, a Baltic pagan witch, in 1866, she became impregnated with the child of a god, and subsequently regained her divinity.'
    },
    {
        id: 'metia-3',
        name: 'Metia',
        image: 'METIA HZ2.jpg',
        height: '5’7” (170 cm)',
        hair_color: 'Dirty-blonde',
        eye_color: 'Grey',
        blood_type: 'Unknown (part god)',
        birth_date: 'Born outside of time in the realm of the Old Gods, but due to her conception in the human world, “born”/able to enter human history on or after 23 June 1866. Metia enters human history on 24 June 1866 at the age of 18 human years, giving her a “constructive” birth date of 23 June 1848.',
        relationships: 'Daughter of Peckols (Old Prussian God of Death) and Christine Gauger when the latter was still a mortal. Mother of Mīlan, Julia, and Luna.',
        additional_info: 'Mother of the Old Gods, known by various names throughout human history including Gaia and Žemyna. Responsible for protecting the Earth and Creation. She was killed ~ 13,500 years ago and reincarnated as the demi-goddess daughter of Christine Gauger.'
    },
    {
        id: 'kevin',
        name: 'Kevin Yamashita Reinholz',
        image: 'KEVIN.jpg',
        height: '5’9” (177 cm)',
        hair_color: 'Dark Brown',
        eye_color: 'Dark Brown',
        blood_type: 'B (Rh Positive)',
        birth_date: '31 March 1981.',
        relationships: 'Descendant of Mīlan and the mortal Emilie Reinholz. Watched (and contacted) by Metia, as well as Julia, who believes him to be the reincarnation of her brother Mīlan.',
        additional_info: 'Fully mortal man, in spite of descent from Metia. Mistaken for the reincarnation of Mīlan, who was killed by Peckols in 1916. Contacted first by Metia, then by Anna Diana, and dutifully transcribed/compiled the records of their previous adventures.'
    },
    {
        id: 'julia',
        name: 'Julia Diana Gauger',
        image: 'JULIA DIANA GAUGER.jpg',
        height: '5’7” (170 cm)',
        hair_color: 'Brown',
        eye_color: 'Grey',
        blood_type: 'Unknown (part god)',
        birth_date: '11 October 1892',
        relationships: 'Daughter of Metia and Gaius Julius Caesar. Sister of Mīlan and Luna. Obsessed with her older brother and, due to her ability to glimpse future events, believes she has found his reincarnation in modern times.',
        additional_info: 'One of the Old Gods, known by various names throughout human history including Tyche, Fortuna, Laima, or simply Fate. She was killed ~ 13,500 years ago and reincarnated as the demi-goddess daughter of Metia. Although she has visions of the future, Julia is known to keep them to herself, as the future is not yet written and “possibilities” can easily confuse or mislead.'
    },
    {
        id: 'amy-strehl',
        name: 'Amy Maria Strehl',
        image: 'AMY MARIA STREHL.jpg',
        height: '5’6” (168 cm)',
        hair_color: 'Brown',
        eye_color: 'Blue',
        blood_type: 'Unknown (part god)',
        birth_date: '4 May 1977',
        relationships: 'Daughter of Anna Diana and Gustav August Strehl. Twin half-sister (fraternal) of Luna, and half-sister of Mīlan.',
        additional_info: 'Reincarnation of a mortal, human soul, but due to her gestation inside the womb of a demi-goddess (Anna Diana), and having a reincarnated goddess (Luna) as a twin, Amy is born a demi-goddess. Normally calm and collected, she is a brilliant medical doctor in the United States of America, where she researches and attempts to cure rare and little understood diseases, but is also known to “cheat” on occasion and use her magic to heal trauma patients.'
    },
    {
        id: 'luna',
        name: 'Luna',
        image: 'LUNA.jpg',
        height: '5’7” (170 cm)',
        hair_color: 'Dirty-blonde',
        eye_color: 'Blue',
        blood_type: 'Unknown (part god)',
        birth_date: '4 May 1977',
        relationships: 'Daughter of Anna Diana and Metia (conceived through the use of magic). Twin half-sister (fraternal) of Amy, and half-sister of Mīlan and Julia.',
        additional_info: 'One of the Old Gods, known by various names throughout human history including Selene and Luna. She was killed during the war between the Old Gods and the “partisans,” and reincarnated as the demi-goddess daughter of Metia and Anna Diana after Metia magically implanted her own seed in Anna Diana’s womb while helping the latter to conceive Amy. Luna is outgoing and flamboyant, but also a brilliant physicist who seeks to explain magical phenomena in scientific terms.'
    },
    {
        id: 'milan',
        name: 'Mīlan',
        image: 'MILAN.jpg',
        height: '5’9” (177 cm)',
        hair_color: 'Blonde',
        eye_color: 'Grey',
        blood_type: 'B (Rh Positive)',
        birth_date: '13 October 1867, but born outside of time in the realm of the Old Gods, where he spent the first 10 years of his life.  As a result, he has a “constructive” birth date of 13 October 1857.',
        relationships: 'Son of Gustav Strehl and Metia. Half-brother of Julia, Amy, and Luna, and distant ancestor of Kevin.',
        additional_info: 'Mīlan was presumed to have died after he took a killing curse from the God of Death intended for his mother in 1916. Although mortal, he is visible simultaneously in both the Visible (material) World and the Invisible (spiritual) World, and imbued with magical abilities primarily relating to fire.  Unlike other mortal users of magic, he does not require the aid of a familiar spirit to work his magic.'
    },
    {
        id: 'celeste',
        name: 'Celeste',
        image: 'CELESTE.jpg',
        height: '5’9” (177 cm)',
        hair_color: 'Black',
        eye_color: 'Lavender',
        blood_type: 'Unknown (fallen angel)',
        birth_date: 'Born outside of time in the realm of the Angels, approximately 500 million years old by human reckoning.',
        relationships: 'Servant of Naamah, a higher-ranking demon, as well as the Devil. She also has a historical connection with Metia’s family, but she is reluctant to speak of it.',
        additional_info: 'A fallen angel, or demon, Celeste once dwelt in the timeless realm of the Angels, connected to Paradise, but was seduced by the Devil’s lies and chose to fall, becoming a servant (and inmate) of Hell.'
    },
    {
        id: 'naamah',
        name: 'Naamah',
        image: 'NAAMAH.jpg',
        height: '5’11” (180 cm)',
        hair_color: 'Blonde',
        eye_color: 'Ice blue',
        blood_type: 'Unknown (fallen angel)',
        birth_date: 'Born outside of time in the realm of the Angels, approximately 500 million years old by human reckoning.',
        relationships: 'Mother of Asmodeus, a Prince of Hell and one of four arch-demons second only in power and authority to the Devil.',
        additional_info: 'Formerly the Angel of Prostitution, Naamah specializes in seduction and lust, and like her son, Asmodeus, has insatiable appetites. As the mother of one of the arch-demons, Naamah enjoys considerable privilege in Hell, but she is ambitious and always looking to increase her standing.'
    }
]